<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<AssemblyName>SimpleMendingYourself</AssemblyName>
		<RootNamespace>SimpleMendingYourself</RootNamespace>
		<DebugType>None</DebugType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<PropertyGroup>
		<ModDir>$(MSBuildProjectDirectory)\..\..\</ModDir>
		<RimWorldManagedDir Condition="'$(RimWorldManagedDir)' == ''">$(MSBuildProjectDirectory)\..\..\..\..\..\..\App\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed</RimWorldManagedDir>
		<SimpleMendingAssemblyPath Condition="'$(SimpleMendingAssemblyPath)' == ''">$(MSBuildProjectDirectory)\..\..\..\..\..\..\App\Steam\steamapps\workshop\content\294100\3657705987\1.6\Assemblies\ComfyCuddlesWithEuterpe.dll</SimpleMendingAssemblyPath>
	</PropertyGroup>

	<ItemGroup Condition="'$(UseReferencePackages)' == 'true'">
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4871" PrivateAssets="all" />
		<Reference Include="ComfyCuddlesWithEuterpe">
			<HintPath>$(SimpleMendingAssemblyPath)</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup Condition="'$(UseReferencePackages)' != 'true'">
		<Reference Include="Assembly-CSharp">
			<HintPath>$(RimWorldManagedDir)\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="ComfyCuddlesWithEuterpe">
		  <HintPath>$(SimpleMendingAssemblyPath)</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(RimWorldManagedDir)\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(RimWorldManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(RimWorldManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SkipModCopy)' != 'true'">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModDir)\Assemblies\" />
	</Target>

	<Target Name="DeployRelease" AfterTargets="PostBuild" Condition="'$(DeployToGame)' == 'true'">
		<PropertyGroup>
			<DeployDir>D:\App\Steam\steamapps\common\RimWorld\Mods\SimpleMendingYourself\</DeployDir>
		</PropertyGroup>
		<RemoveDir Directories="$(DeployDir)" />
		<ItemGroup>
			<ReleaseFiles Include="$(ModDir)**\*"
				Exclude="$(ModDir)Source\**;$(ModDir).git\**;$(ModDir).idea\**;$(ModDir).gitignore;$(ModDir)**\.gitkeep" />
		</ItemGroup>
		<Copy SourceFiles="@(ReleaseFiles)"
			DestinationFiles="@(ReleaseFiles->'$(DeployDir)%(RecursiveDir)%(Filename)%(Extension)')" />
	</Target>

</Project>
